### ISSUE TITLE
[Feature REQ] Uptime Command and etc

### ISSUE THREAD

**Issue by Anon0ne** [v0idp/Mellow#119]
Hello! I will try and spare some time to work on this but I want to get a command to show uptime of the docker container or the host PC if possible. Maybe even sprinkle in container health/image version.

Like !uptime and !status commands which I had on old-school battle.net bots for StarCraft and Diablo 2. They had a ton of useful features including being able to chat from the interface. Send invites via email address, and more.

Also would like to add some other commands and expand this to be able to do light moderation. Then I only need 1 bot in chats.

I am curious about what happens when ombi already has an item available but other episodes in the season are missing. It would be great to break that down somehow.

**Comment by v0idp** [comment]
Mellow was never intended to offer any functionality beyond communicating and using features from the APIs like sonarr, radarr, ombi, tautulli and so on. that's why I never bothered adding any other commands which go beyond that. Same goes for moderational commands.

Feel free to create your fork and add those functionalities tho!

The way I currently handle requests is that I always request the whole show/tv series. If it's already in sonarr/ombi. it can't be requested. So there is no functionality in there yet for individual seasons and episodes. It would be great to have this tho!

**Comment by Anon0ne** [comment]
Okay. I'll see if there's anything I can help with on individual episodes. Thanks for reply.
